# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-30 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area', to='consumption.Area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff', to='consumption.Tariff'),
        ),
    ]
